package POJOs;
// Generated 09-Jul-2020 22:31:57 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Conference generated by hbm2java
 */
@Entity
@Table(name="conference"
    ,catalog="conference_manager"
)
public class Conference  implements java.io.Serializable {


     private Integer idHoiNghi;
     private Location location;
     private String ten;
     private String moTaNgan;
     private String moTaChiTiet;
     private String hinhAnh;
     private Date thoiGian;
     private int ngThamDu;
     private Set accounts = new HashSet(0);

    public Conference() {
    }

	
    public Conference(Location location, String ten, String moTaNgan, String moTaChiTiet, String hinhAnh, Date thoiGian, int ngThamDu) {
        this.location = location;
        this.ten = ten;
        this.moTaNgan = moTaNgan;
        this.moTaChiTiet = moTaChiTiet;
        this.hinhAnh = hinhAnh;
        this.thoiGian = thoiGian;
        this.ngThamDu = ngThamDu;
    }
    public Conference(Location location, String ten, String moTaNgan, String moTaChiTiet, String hinhAnh, Date thoiGian, int ngThamDu, Set accounts) {
       this.location = location;
       this.ten = ten;
       this.moTaNgan = moTaNgan;
       this.moTaChiTiet = moTaChiTiet;
       this.hinhAnh = hinhAnh;
       this.thoiGian = thoiGian;
       this.ngThamDu = ngThamDu;
       this.accounts = accounts;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idHoiNghi", unique=true, nullable=false)
    public Integer getIdHoiNghi() {
        return this.idHoiNghi;
    }
    
    public void setIdHoiNghi(Integer idHoiNghi) {
        this.idHoiNghi = idHoiNghi;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="DiaDiem", nullable=false)
    public Location getLocation() {
        return this.location;
    }
    
    public void setLocation(Location location) {
        this.location = location;
    }

    
    @Column(name="Ten", nullable=false, length=45)
    public String getTen() {
        return this.ten;
    }
    
    public void setTen(String ten) {
        this.ten = ten;
    }

    
    @Column(name="MoTaNgan", nullable=false, length=100)
    public String getMoTaNgan() {
        return this.moTaNgan;
    }
    
    public void setMoTaNgan(String moTaNgan) {
        this.moTaNgan = moTaNgan;
    }

    
    @Column(name="MoTaChiTiet", nullable=false, length=500)
    public String getMoTaChiTiet() {
        return this.moTaChiTiet;
    }
    
    public void setMoTaChiTiet(String moTaChiTiet) {
        this.moTaChiTiet = moTaChiTiet;
    }

    
    @Column(name="HinhAnh", nullable=false, length=45)
    public String getHinhAnh() {
        return this.hinhAnh;
    }
    
    public void setHinhAnh(String hinhAnh) {
        this.hinhAnh = hinhAnh;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ThoiGian", nullable=false, length=19)
    public Date getThoiGian() {
        return this.thoiGian;
    }
    
    public void setThoiGian(Date thoiGian) {
        this.thoiGian = thoiGian;
    }

    
    @Column(name="NgThamDu", nullable=false)
    public int getNgThamDu() {
        return this.ngThamDu;
    }
    
    public void setNgThamDu(int ngThamDu) {
        this.ngThamDu = ngThamDu;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="user_hoinghi", catalog="conference_manager", joinColumns = { 
        @JoinColumn(name="idHoiNghi", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="idUser", nullable=false, updatable=false) })
    public Set getAccounts() {
        return this.accounts;
    }
    
    public void setAccounts(Set accounts) {
        this.accounts = accounts;
    }




}


