package POJOs;
// Generated 15-Jul-2020 14:10:35 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserHoinghi generated by hbm2java
 */
@Entity
@Table(name="user_hoinghi"
    ,catalog="conference_manager"
)
public class UserHoinghi  implements java.io.Serializable {


     private UserHoinghiId id;
     private Account account;
     private Conference conference;
     private int status;

    public UserHoinghi() {
    }

    public UserHoinghi(UserHoinghiId id, Account account, Conference conference, int status) {
       this.id = id;
       this.account = account;
       this.conference = conference;
       this.status = status;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idHoiNghi", column=@Column(name="idHoiNghi", nullable=false) ), 
        @AttributeOverride(name="idUser", column=@Column(name="idUser", nullable=false) ) } )
    public UserHoinghiId getId() {
        return this.id;
    }
    
    public void setId(UserHoinghiId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idUser", nullable=false, insertable=false, updatable=false)
    public Account getAccount() {
        return this.account;
    }
    
    public void setAccount(Account account) {
        this.account = account;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idHoiNghi", nullable=false, insertable=false, updatable=false)
    public Conference getConference() {
        return this.conference;
    }
    
    public void setConference(Conference conference) {
        this.conference = conference;
    }

    
    @Column(name="status", nullable=false)
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }


}


