package POJOs;
// Generated 15-Jul-2020 14:10:35 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Account generated by hbm2java
 */
@Entity
@Table(name="account"
    ,catalog="conference_manager"
)
public class Account  implements java.io.Serializable {


     private Integer idAccount;
     private String ten;
     private String username;
     private String password;
     private String email;
     private int accountType;
     private int isActive;
     private Set userHoinghis = new HashSet(0);

    public Account() {
    }

	
    public Account(String ten, String username, String password, String email, int accountType, int isActive) {
        this.ten = ten;
        this.username = username;
        this.password = password;
        this.email = email;
        this.accountType = accountType;
        this.isActive = isActive;
    }
    public Account(String ten, String username, String password, String email, int accountType, int isActive, Set userHoinghis) {
       this.ten = ten;
       this.username = username;
       this.password = password;
       this.email = email;
       this.accountType = accountType;
       this.isActive = isActive;
       this.userHoinghis = userHoinghis;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idAccount", unique=true, nullable=false)
    public Integer getIdAccount() {
        return this.idAccount;
    }
    
    public void setIdAccount(Integer idAccount) {
        this.idAccount = idAccount;
    }

    
    @Column(name="Ten", nullable=false, length=45)
    public String getTen() {
        return this.ten;
    }
    
    public void setTen(String ten) {
        this.ten = ten;
    }

    
    @Column(name="Username", nullable=false, length=45)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="Password", nullable=false, length=45)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="Email", nullable=false, length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="accountType", nullable=false)
    public int getAccountType() {
        return this.accountType;
    }
    
    public void setAccountType(int accountType) {
        this.accountType = accountType;
    }

    
    @Column(name="isActive", nullable=false)
    public int getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(int isActive) {
        this.isActive = isActive;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="account")
    public Set getUserHoinghis() {
        return this.userHoinghis;
    }
    
    public void setUserHoinghis(Set userHoinghis) {
        this.userHoinghis = userHoinghis;
    }




}


