package POJOs;
// Generated 15-Jul-2020 14:10:35 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Location generated by hbm2java
 */
@Entity
@Table(name="location"
    ,catalog="conference_manager"
)
public class Location  implements java.io.Serializable {


     private Integer idDiaDiem;
     private String ten;
     private String diaChi;
     private int sucChua;
     private Set conferences = new HashSet(0);

    public Location() {
    }

	
    public Location(String ten, String diaChi, int sucChua) {
        this.ten = ten;
        this.diaChi = diaChi;
        this.sucChua = sucChua;
    }
    public Location(String ten, String diaChi, int sucChua, Set conferences) {
       this.ten = ten;
       this.diaChi = diaChi;
       this.sucChua = sucChua;
       this.conferences = conferences;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idDiaDiem", unique=true, nullable=false)
    public Integer getIdDiaDiem() {
        return this.idDiaDiem;
    }
    
    public void setIdDiaDiem(Integer idDiaDiem) {
        this.idDiaDiem = idDiaDiem;
    }

    
    @Column(name="Ten", nullable=false, length=45)
    public String getTen() {
        return this.ten;
    }
    
    public void setTen(String ten) {
        this.ten = ten;
    }

    
    @Column(name="DiaChi", nullable=false, length=100)
    public String getDiaChi() {
        return this.diaChi;
    }
    
    public void setDiaChi(String diaChi) {
        this.diaChi = diaChi;
    }

    
    @Column(name="SucChua", nullable=false)
    public int getSucChua() {
        return this.sucChua;
    }
    
    public void setSucChua(int sucChua) {
        this.sucChua = sucChua;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="location")
    public Set getConferences() {
        return this.conferences;
    }
    
    public void setConferences(Set conferences) {
        this.conferences = conferences;
    }




}


