/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Panel;

import DAO.ConferenceDAO;
import POJOs.Conference;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author hungh
 */
public class cardViewConference extends javax.swing.JPanel {

    /**
     * Creates new form cardViewConference
     */
    public cardViewConference() {
        initComponents();
    }

    public cardViewConference(int id) {
        initComponents();
        settingUp(id);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        imageLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setMaximumSize(new java.awt.Dimension(226, 200));
        setMinimumSize(new java.awt.Dimension(226, 200));
        setPreferredSize(new java.awt.Dimension(226, 200));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());

        imageLabel.setBackground(new java.awt.Color(255, 255, 255));
        imageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(imageLabel, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(226, 30));
        jPanel2.setMinimumSize(new java.awt.Dimension(226, 30));
        jPanel2.setPreferredSize(new java.awt.Dimension(226, 30));
        jPanel2.setLayout(new java.awt.BorderLayout());

        nameLabel.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabel.setText("Name of Conference");
        jPanel2.add(nameLabel, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imageLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel nameLabel;
    // End of variables declaration//GEN-END:variables

    private void settingUp(int id) {
        Conference temp = ConferenceDAO.getConference(id);
        String nameConference = temp.getTen();
        String imageConference = temp.getHinhAnh();
        
        try
        {
            ImageIcon img = new javax.swing.ImageIcon(getClass().getResource(imageConference));
            Image newImg = img.getImage().getScaledInstance(226, 160, Image.SCALE_DEFAULT);
            ImageIcon setLabel = new ImageIcon(newImg);
            imageLabel.setIcon(setLabel);
        }catch(NullPointerException ex){}   
        nameLabel.setText(nameConference);
    }
}
