/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import UI.panelHandling.listViewConference;
import DAO.ConferenceDAO;
import File.SupportFile;
import POJOs.Conference;
import POJOs.Location;
import UI.panelHandling.cardViewConference;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Image;
import java.awt.LayoutManager;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.text.DefaultCaret;

/**
 *
 * @author hungh
 */
public class MainScreen extends javax.swing.JFrame {

    /**
     * Creates new form MainScreen
     */
    
    int typeView = 0;  //0: list view. 1: card view
    int typeUser = -1;  //-1: not logged in. 0:admin. 1: user
    
    public MainScreen() {
        initComponents();
        displaySidePanel();
        initDataFromDB();
        navigatorPanel.setVisible(false);
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        HomePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        conferenceListPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        statisticsPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        conferenceManagementPanel = new javax.swing.JPanel();
        conferenceManagementLabel = new javax.swing.JLabel();
        userManagementPanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        profilePanel = new javax.swing.JPanel();
        profileLabel = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        signInPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        navigatorPanel = new javax.swing.JPanel();
        cardViewButton = new javax.swing.JLabel();
        listViewButton = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        parentCardLayout = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        listViewScrollPane = new javax.swing.JScrollPane();
        listConferencePanel = new javax.swing.JPanel();
        cardViewScrollPane = new javax.swing.JScrollPane();
        cardConferencePanel = new javax.swing.JPanel();
        detailConferenceScrollPane = new javax.swing.JScrollPane();
        detailConferencePanel = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        backToListLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        detailImageLabel = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        detailNameLabel = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        detailDescriptionLabel = new javax.swing.JTextArea();
        jPanel13 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        detailTimeLabel = new javax.swing.JLabel();
        detailLocationLabel = new javax.swing.JLabel();
        detailMemberLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 500));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 50));

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/meeting.png"))); // NOI18N
        jLabel1.setText("Conference");
        jPanel2.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.PAGE_AXIS));

        HomePanel.setBackground(new java.awt.Color(204, 255, 204));
        HomePanel.setMaximumSize(new java.awt.Dimension(200, 45));
        HomePanel.setMinimumSize(new java.awt.Dimension(200, 45));
        HomePanel.setPreferredSize(new java.awt.Dimension(200, 45));
        HomePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomePanelMouseClicked(evt);
            }
        });
        HomePanel.setLayout(new java.awt.BorderLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setText("Home");
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        HomePanel.add(jLabel2, java.awt.BorderLayout.CENTER);

        jPanel4.add(HomePanel);

        conferenceListPanel.setBackground(new java.awt.Color(0, 255, 0));
        conferenceListPanel.setMaximumSize(new java.awt.Dimension(200, 45));
        conferenceListPanel.setMinimumSize(new java.awt.Dimension(200, 45));
        conferenceListPanel.setPreferredSize(new java.awt.Dimension(125, 45));
        conferenceListPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                conferenceListPanelMouseClicked(evt);
            }
        });
        conferenceListPanel.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel3.setText("Conference List");
        jLabel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        conferenceListPanel.add(jLabel3, java.awt.BorderLayout.CENTER);

        jPanel4.add(conferenceListPanel);

        statisticsPanel.setBackground(new java.awt.Color(0, 204, 204));
        statisticsPanel.setMaximumSize(new java.awt.Dimension(200, 45));
        statisticsPanel.setMinimumSize(new java.awt.Dimension(200, 45));
        statisticsPanel.setPreferredSize(new java.awt.Dimension(200, 45));
        statisticsPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                statisticsPanelMouseClicked(evt);
            }
        });
        statisticsPanel.setLayout(new java.awt.BorderLayout());

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel4.setText("Statistics");
        jLabel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        statisticsPanel.add(jLabel4, java.awt.BorderLayout.CENTER);

        jPanel4.add(statisticsPanel);

        conferenceManagementPanel.setBackground(new java.awt.Color(204, 255, 255));
        conferenceManagementPanel.setMaximumSize(new java.awt.Dimension(200, 45));
        conferenceManagementPanel.setMinimumSize(new java.awt.Dimension(200, 45));
        conferenceManagementPanel.setPreferredSize(new java.awt.Dimension(200, 45));
        conferenceManagementPanel.setLayout(new java.awt.BorderLayout());

        conferenceManagementLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        conferenceManagementLabel.setText("Conference Management");
        conferenceManagementLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        conferenceManagementPanel.add(conferenceManagementLabel, java.awt.BorderLayout.CENTER);

        jPanel4.add(conferenceManagementPanel);

        userManagementPanel.setBackground(new java.awt.Color(153, 255, 255));
        userManagementPanel.setMaximumSize(new java.awt.Dimension(200, 45));
        userManagementPanel.setMinimumSize(new java.awt.Dimension(200, 45));
        userManagementPanel.setPreferredSize(new java.awt.Dimension(200, 45));
        userManagementPanel.setLayout(new java.awt.BorderLayout());

        jLabel12.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel12.setText("User Management");
        jLabel12.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        userManagementPanel.add(jLabel12, java.awt.BorderLayout.CENTER);

        jPanel4.add(userManagementPanel);

        profilePanel.setBackground(new java.awt.Color(0, 102, 102));
        profilePanel.setMaximumSize(new java.awt.Dimension(200, 45));
        profilePanel.setMinimumSize(new java.awt.Dimension(200, 45));
        profilePanel.setPreferredSize(new java.awt.Dimension(200, 45));
        profilePanel.setLayout(new java.awt.BorderLayout());

        profileLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        profileLabel.setText("Profile");
        profileLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        profilePanel.add(profileLabel, java.awt.BorderLayout.CENTER);

        jPanel4.add(profilePanel);

        jPanel16.setBackground(new java.awt.Color(51, 255, 255));
        jPanel16.setMaximumSize(new java.awt.Dimension(200, 45));
        jPanel16.setMinimumSize(new java.awt.Dimension(200, 45));
        jPanel16.setPreferredSize(new java.awt.Dimension(200, 45));
        jPanel16.setLayout(new java.awt.BorderLayout());

        jLabel13.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel13.setText("jLabel13");
        jLabel13.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        jPanel16.add(jLabel13, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel16);

        signInPanel.setBackground(new java.awt.Color(0, 204, 0));
        signInPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signInPanelMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel6.setText("Sign In");

        javax.swing.GroupLayout signInPanelLayout = new javax.swing.GroupLayout(signInPanel);
        signInPanel.setLayout(signInPanelLayout);
        signInPanelLayout.setHorizontalGroup(
            signInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(signInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(signInPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        signInPanelLayout.setVerticalGroup(
            signInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(signInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(signInPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        navigatorPanel.setBackground(new java.awt.Color(255, 255, 204));

        cardViewButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/grid.png"))); // NOI18N
        cardViewButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 15));
        cardViewButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cardViewButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cardViewButtonMouseClicked(evt);
            }
        });

        listViewButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/list.png"))); // NOI18N
        listViewButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listViewButtonMouseClicked(evt);
            }
        });

        jTextField1.setVerifyInputWhenFocusTarget(false);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search_b.png"))); // NOI18N

        javax.swing.GroupLayout navigatorPanelLayout = new javax.swing.GroupLayout(navigatorPanel);
        navigatorPanel.setLayout(navigatorPanelLayout);
        navigatorPanelLayout.setHorizontalGroup(
            navigatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navigatorPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(45, 45, 45)
                .addComponent(listViewButton)
                .addGap(18, 18, 18)
                .addComponent(cardViewButton)
                .addGap(4, 4, 4))
        );
        navigatorPanelLayout.setVerticalGroup(
            navigatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigatorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(navigatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1)
                    .addGroup(navigatorPanelLayout.createSequentialGroup()
                        .addGroup(navigatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(navigatorPanelLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel10))
                            .addComponent(cardViewButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(listViewButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        parentCardLayout.setBackground(new java.awt.Color(255, 255, 255));
        parentCardLayout.setLayout(new java.awt.CardLayout());

        jPanel9.setBackground(new java.awt.Color(153, 255, 204));
        jPanel9.setLayout(new java.awt.GridLayout(0, 1, 5, 5));
        parentCardLayout.add(jPanel9, "label");

        jPanel10.setBackground(new java.awt.Color(51, 255, 204));
        jPanel10.setLayout(new java.awt.BorderLayout());

        jButton1.setText("Click here");
        jPanel10.add(jButton1, java.awt.BorderLayout.CENTER);

        parentCardLayout.add(jPanel10, "button");

        listViewScrollPane.setBackground(new java.awt.Color(255, 255, 255));
        listViewScrollPane.setBorder(null);
        listViewScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        listConferencePanel.setBackground(new java.awt.Color(255, 255, 255));
        listConferencePanel.setLayout(new java.awt.GridLayout(0, 1, 0, 10));
        listViewScrollPane.setViewportView(listConferencePanel);

        parentCardLayout.add(listViewScrollPane, "card5");

        cardViewScrollPane.setBackground(new java.awt.Color(255, 255, 255));
        cardViewScrollPane.setBorder(null);
        cardViewScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        cardConferencePanel.setLayout(new java.awt.GridLayout(0, 3, 10, 10));
        cardViewScrollPane.setViewportView(cardConferencePanel);

        parentCardLayout.add(cardViewScrollPane, "card6");

        detailConferenceScrollPane.setBorder(null);
        detailConferenceScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        detailConferenceScrollPane.setPreferredSize(new java.awt.Dimension(794, 444));

        detailConferencePanel.setBackground(new java.awt.Color(255, 255, 255));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setPreferredSize(new java.awt.Dimension(0, 35));

        backToListLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        backToListLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
        backToListLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backToListLabelMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        jLabel7.setText("Enroll Now");
        jLabel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(backToListLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(18, 18, 18))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(backToListLabel))
                .addGap(0, 1, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        detailImageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(detailImageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(detailImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setPreferredSize(new java.awt.Dimension(794, 50));
        jPanel8.setLayout(new java.awt.BorderLayout());

        detailNameLabel.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        detailNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        detailNameLabel.setText("Name of Conference");
        detailNameLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel8.add(detailNameLabel, java.awt.BorderLayout.CENTER);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setLayout(new java.awt.BorderLayout());

        detailDescriptionLabel.setEditable(false);
        detailDescriptionLabel.setColumns(20);
        detailDescriptionLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        detailDescriptionLabel.setRows(5);
        detailDescriptionLabel.setAutoscrolls(false);
        detailDescriptionLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        jScrollPane2.setViewportView(detailDescriptionLabel);

        jPanel12.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        jPanel13.setLayout(new java.awt.GridLayout(0, 1));

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabel11.setText("Thông tin tham gia:");
        jPanel13.add(jLabel11);

        detailTimeLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        detailTimeLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        detailTimeLabel.setText("Time");
        jPanel13.add(detailTimeLabel);

        detailLocationLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        detailLocationLabel.setText("Location");
        jPanel13.add(detailLocationLabel);

        detailMemberLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        detailMemberLabel.setText("jLabel14");
        jPanel13.add(detailMemberLabel);

        javax.swing.GroupLayout detailConferencePanelLayout = new javax.swing.GroupLayout(detailConferencePanel);
        detailConferencePanel.setLayout(detailConferencePanelLayout);
        detailConferencePanelLayout.setHorizontalGroup(
            detailConferencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, 797, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 797, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detailConferencePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        detailConferencePanelLayout.setVerticalGroup(
            detailConferencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailConferencePanelLayout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
        );

        detailConferenceScrollPane.setViewportView(detailConferencePanel);

        parentCardLayout.add(detailConferenceScrollPane, "card5");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(navigatorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(parentCardLayout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(navigatorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parentCardLayout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(signInPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(signInPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void HomePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomePanelMouseClicked
        // TODO add your handling code here:
        navigatorPanel.setVisible(false);
    }//GEN-LAST:event_HomePanelMouseClicked

    private void conferenceListPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_conferenceListPanelMouseClicked
        // TODO add your handling code here:        
        navigatorPanel.setVisible(true);
        parentCardLayout.removeAll();
        parentCardLayout.add(listViewScrollPane);
        parentCardLayout.repaint();
        parentCardLayout.revalidate();
    }//GEN-LAST:event_conferenceListPanelMouseClicked

    private void statisticsPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statisticsPanelMouseClicked
        // TODO add your handling code here:
        navigatorPanel.setVisible(true);
        parentCardLayout.removeAll();
        parentCardLayout.add(jPanel10);
        parentCardLayout.repaint();
        parentCardLayout.revalidate();
    }//GEN-LAST:event_statisticsPanelMouseClicked

    private void signInPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signInPanelMouseClicked
        // TODO add your handling code here:
        LoginScreen loginDialog = new LoginScreen(this, rootPaneCheckingEnabled);
        loginDialog.setVisible(true);
        
        typeUser = loginDialog.getTypeAccount();
        displaySidePanel();  
        System.out.println("account: " + typeUser);
    }//GEN-LAST:event_signInPanelMouseClicked

    private void backToListLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backToListLabelMouseClicked
        // TODO add your handling code here:
        conferenceListPanelMouseClicked(evt);
    }//GEN-LAST:event_backToListLabelMouseClicked

    private void cardViewButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardViewButtonMouseClicked
        // TODO add your handling code here:
        navigatorPanel.setVisible(true);
        parentCardLayout.removeAll();
        parentCardLayout.add(cardViewScrollPane);
        parentCardLayout.repaint();
        parentCardLayout.revalidate();
        
    }//GEN-LAST:event_cardViewButtonMouseClicked

    private void listViewButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listViewButtonMouseClicked
        // TODO add your handling code here:
        navigatorPanel.setVisible(true);
        parentCardLayout.removeAll();
        parentCardLayout.add(listViewScrollPane);
        parentCardLayout.repaint();
        parentCardLayout.revalidate();
    }//GEN-LAST:event_listViewButtonMouseClicked

    private void setDetailConferencePanel(Conference conference)
    {
        detailConferenceScrollPane.getVerticalScrollBar().setUnitIncrement(20);
        navigatorPanel.setVisible(false);
        backToListLabel.setAutoscrolls(false);
        
        
        String image = conference.getHinhAnh();
        String name = conference.getTen();
        String detail = conference.getMoTaChiTiet();
        Date d = conference.getThoiGian();
        String time = String.valueOf("Thời gian: " +SupportFile.getCustomTimeString(d));
        Location l = conference.getLocation();
        String location = String.valueOf("Địa điểm: "+l.getTen() + " - " + l.getDiaChi());
        int m = conference.getNgThamDu();
        String member = String.valueOf("Số người tham dự: "+m);
        
        ImageIcon img = new javax.swing.ImageIcon(getClass().getResource(image));
        Image newImg = img.getImage().getScaledInstance(775, 500, Image.SCALE_DEFAULT);
        ImageIcon setLabel = new ImageIcon(newImg);
        
        detailImageLabel.setIcon(setLabel);
        detailDescriptionLabel.setText(detail);
        detailDescriptionLabel.setLineWrap(true);
        detailDescriptionLabel.setWrapStyleWord(true);
        detailNameLabel.setText(name);
        detailTimeLabel.setText(time);
        detailLocationLabel.setText(location);
        detailMemberLabel.setText(member);
    }
    
    private void displaySidePanel()
    {
        switch (typeUser) {
        // not logged in
            case -1:
                setStateSidePanel(false);
                break;
        // admin
            case 0:
                setStateSidePanel(true);
                break;
        // user
            case 1:
                setStateSidePanel(false);
                statisticsPanel.setVisible(true);
                profilePanel.setVisible(true);
                break;
            default:
                break;
        }
    }
    
    
    private void setStateSidePanel(boolean b)
    {
        jPanel16.setVisible(b);
        statisticsPanel.setVisible(b);
        conferenceManagementPanel.setVisible(b);
        userManagementPanel.setVisible(b);
        profilePanel.setVisible(b);
    }
    
    private void initDataFromDB()
    {
        cardViewScrollPane.getVerticalScrollBar().setUnitIncrement(15);
        cardConferencePanel.removeAll();
        listViewScrollPane.getVerticalScrollBar().setUnitIncrement(15);
        listConferencePanel.removeAll();
        
        navigatorPanel.setVisible(true);
        
        List<Conference> listConference = ConferenceDAO.getListConference();
        int sizeList = listConference.size();
        
        if(sizeList > 0)
        {
            for(int i = 0; i< sizeList; i++)
            {
                Conference c = listConference.get(i);
                int id = c.getIdHoiNghi();
                JPanel j1 = new cardViewConference(id);
                j1.addMouseListener(new MouseAdapter() {
                    @Override
                    public void mouseClicked(MouseEvent e) {
                        setDetailConferencePanel(c);
                        parentCardLayout.removeAll();
                        parentCardLayout.add(detailConferenceScrollPane);
                        parentCardLayout.repaint();
                        parentCardLayout.revalidate();
                    }
                });
                
                JPanel j2 = new listViewConference(id);
                j2.addMouseListener(new MouseAdapter() {
                    @Override
                    public void mouseClicked(MouseEvent e) {
                        setDetailConferencePanel(c);
                        parentCardLayout.removeAll();
                        parentCardLayout.add(detailConferenceScrollPane);
                        parentCardLayout.repaint();
                        parentCardLayout.revalidate();
                    }
                    
                });
                //jPanel.setCursor(new Cursor(Cursor.HAND_CURSOR));
                cardConferencePanel.add(j1);
                listConferencePanel.add(j2);
            }
        }
        else
        {
            JLabel noti = new JLabel("Không có hội nghị nào diễn ra!");
            listConferencePanel.add(noti, BorderLayout.CENTER);
        }

    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try
                {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                    new MainScreen().setVisible(true);
                }catch(Exception e)
                {
                    new MainScreen().setVisible(true);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HomePanel;
    private javax.swing.JLabel backToListLabel;
    private javax.swing.JPanel cardConferencePanel;
    private javax.swing.JLabel cardViewButton;
    private javax.swing.JScrollPane cardViewScrollPane;
    private javax.swing.JPanel conferenceListPanel;
    private javax.swing.JLabel conferenceManagementLabel;
    private javax.swing.JPanel conferenceManagementPanel;
    private javax.swing.JPanel detailConferencePanel;
    private javax.swing.JScrollPane detailConferenceScrollPane;
    private javax.swing.JTextArea detailDescriptionLabel;
    private javax.swing.JLabel detailImageLabel;
    private javax.swing.JLabel detailLocationLabel;
    private javax.swing.JLabel detailMemberLabel;
    private javax.swing.JLabel detailNameLabel;
    private javax.swing.JLabel detailTimeLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel listConferencePanel;
    private javax.swing.JLabel listViewButton;
    private javax.swing.JScrollPane listViewScrollPane;
    private javax.swing.JPanel navigatorPanel;
    private javax.swing.JPanel parentCardLayout;
    private javax.swing.JLabel profileLabel;
    private javax.swing.JPanel profilePanel;
    private javax.swing.JPanel signInPanel;
    private javax.swing.JPanel statisticsPanel;
    private javax.swing.JPanel userManagementPanel;
    // End of variables declaration//GEN-END:variables
}


