/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import DAO.AccountDAO;
import UI.panelHandling.listViewConference;
import DAO.ConferenceDAO;
import File.SupportFile;
import POJOs.Account;
import POJOs.Conference;
import POJOs.Location;
import UI.panelHandling.cardViewConference;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Image;
import java.awt.LayoutManager;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.security.NoSuchAlgorithmException;
import java.util.Date;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.UIManager;

/**
 *
 * @author hungh
 */
public class MainScreen extends javax.swing.JFrame {

    /**
     * Creates new form MainScreen
     */
    
    int typeView = 0;  //0: list view. 1: card view
    int typeUser = -1;  //-1: not logged in. 0:admin. 1: user
    Account account = null;
    
    public MainScreen() {
        initComponents();
        displaySidePanel();
        initDataFromDB();
        settingComponents();
        navigatorPanel.setVisible(false);
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rootPanel = new javax.swing.JPanel();
        logoPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        sidePanel = new javax.swing.JPanel();
        homeSidePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        conferenceListSidePanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        statisticsSidePanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        conferenceManagementSidePanel = new javax.swing.JPanel();
        conferenceManagementLabel = new javax.swing.JLabel();
        userManagementSidePanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        profileSidePanel = new javax.swing.JPanel();
        profileLabel = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        signInPanel = new javax.swing.JPanel();
        signInLabel = new javax.swing.JLabel();
        contentPanel = new javax.swing.JPanel();
        navigatorPanel = new javax.swing.JPanel();
        cardViewButton = new javax.swing.JLabel();
        listViewButton = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        parentCardLayout = new javax.swing.JPanel();
        homePanel = new javax.swing.JPanel();
        statisticsPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        listViewScrollPane = new javax.swing.JScrollPane();
        listConferencePanel = new javax.swing.JPanel();
        cardViewScrollPane = new javax.swing.JScrollPane();
        cardConferencePanel = new javax.swing.JPanel();
        detailConferenceScrollPane = new javax.swing.JScrollPane();
        detailConferencePanel = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        backToListLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        detailImageLabel = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        detailNameLabel = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        detailDescriptionLabel = new javax.swing.JTextArea();
        jPanel13 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        detailTimeLabel = new javax.swing.JLabel();
        detailLocationLabel = new javax.swing.JLabel();
        detailMemberLabel = new javax.swing.JLabel();
        profilePanel = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        yourProfileLabel = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        profile_emailLabel = new javax.swing.JTextField();
        profile_nameLabel = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        profile_usrnameLabel = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        profile_oldpassLabel = new javax.swing.JPasswordField();
        profile_newPassLabel = new javax.swing.JPasswordField();
        profile_reNewPassLabel = new javax.swing.JPasswordField();
        profile_updateButton = new javax.swing.JButton();
        profile_defaultButton = new javax.swing.JButton();
        conferenceManagementPanel = new javax.swing.JPanel();
        userManagementPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 500));

        rootPanel.setBackground(new java.awt.Color(255, 255, 255));
        rootPanel.setPreferredSize(new java.awt.Dimension(1000, 50));

        logoPanel.setBackground(new java.awt.Color(0, 153, 255));
        logoPanel.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/meeting.png"))); // NOI18N
        jLabel1.setText("Conference");
        logoPanel.add(jLabel1, java.awt.BorderLayout.CENTER);

        sidePanel.setBackground(new java.awt.Color(0, 153, 153));
        sidePanel.setLayout(new javax.swing.BoxLayout(sidePanel, javax.swing.BoxLayout.PAGE_AXIS));

        homeSidePanel.setBackground(new java.awt.Color(204, 255, 204));
        homeSidePanel.setMaximumSize(new java.awt.Dimension(200, 45));
        homeSidePanel.setMinimumSize(new java.awt.Dimension(200, 45));
        homeSidePanel.setPreferredSize(new java.awt.Dimension(200, 45));
        homeSidePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeSidePanelMouseClicked(evt);
            }
        });
        homeSidePanel.setLayout(new java.awt.BorderLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setText("Home");
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        homeSidePanel.add(jLabel2, java.awt.BorderLayout.CENTER);

        sidePanel.add(homeSidePanel);

        conferenceListSidePanel.setBackground(new java.awt.Color(0, 255, 0));
        conferenceListSidePanel.setMaximumSize(new java.awt.Dimension(200, 45));
        conferenceListSidePanel.setMinimumSize(new java.awt.Dimension(200, 45));
        conferenceListSidePanel.setPreferredSize(new java.awt.Dimension(125, 45));
        conferenceListSidePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                conferenceListSidePanelMouseClicked(evt);
            }
        });
        conferenceListSidePanel.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel3.setText("Conference List");
        jLabel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        conferenceListSidePanel.add(jLabel3, java.awt.BorderLayout.CENTER);

        sidePanel.add(conferenceListSidePanel);

        statisticsSidePanel.setBackground(new java.awt.Color(0, 204, 204));
        statisticsSidePanel.setMaximumSize(new java.awt.Dimension(200, 45));
        statisticsSidePanel.setMinimumSize(new java.awt.Dimension(200, 45));
        statisticsSidePanel.setPreferredSize(new java.awt.Dimension(200, 45));
        statisticsSidePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                statisticsSidePanelMouseClicked(evt);
            }
        });
        statisticsSidePanel.setLayout(new java.awt.BorderLayout());

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel4.setText("Statistics");
        jLabel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        statisticsSidePanel.add(jLabel4, java.awt.BorderLayout.CENTER);

        sidePanel.add(statisticsSidePanel);

        conferenceManagementSidePanel.setBackground(new java.awt.Color(204, 255, 255));
        conferenceManagementSidePanel.setMaximumSize(new java.awt.Dimension(200, 45));
        conferenceManagementSidePanel.setMinimumSize(new java.awt.Dimension(200, 45));
        conferenceManagementSidePanel.setPreferredSize(new java.awt.Dimension(200, 45));
        conferenceManagementSidePanel.setLayout(new java.awt.BorderLayout());

        conferenceManagementLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        conferenceManagementLabel.setText("Conference Management");
        conferenceManagementLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        conferenceManagementSidePanel.add(conferenceManagementLabel, java.awt.BorderLayout.CENTER);

        sidePanel.add(conferenceManagementSidePanel);

        userManagementSidePanel.setBackground(new java.awt.Color(153, 255, 255));
        userManagementSidePanel.setMaximumSize(new java.awt.Dimension(200, 45));
        userManagementSidePanel.setMinimumSize(new java.awt.Dimension(200, 45));
        userManagementSidePanel.setPreferredSize(new java.awt.Dimension(200, 45));
        userManagementSidePanel.setLayout(new java.awt.BorderLayout());

        jLabel12.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel12.setText("User Management");
        jLabel12.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        userManagementSidePanel.add(jLabel12, java.awt.BorderLayout.CENTER);

        sidePanel.add(userManagementSidePanel);

        profileSidePanel.setBackground(new java.awt.Color(0, 102, 102));
        profileSidePanel.setMaximumSize(new java.awt.Dimension(200, 45));
        profileSidePanel.setMinimumSize(new java.awt.Dimension(200, 45));
        profileSidePanel.setPreferredSize(new java.awt.Dimension(200, 45));
        profileSidePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileSidePanelMouseClicked(evt);
            }
        });
        profileSidePanel.setLayout(new java.awt.BorderLayout());

        profileLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        profileLabel.setText("Profile");
        profileLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        profileSidePanel.add(profileLabel, java.awt.BorderLayout.CENTER);

        sidePanel.add(profileSidePanel);

        jPanel16.setBackground(new java.awt.Color(51, 255, 255));
        jPanel16.setMaximumSize(new java.awt.Dimension(200, 45));
        jPanel16.setMinimumSize(new java.awt.Dimension(200, 45));
        jPanel16.setPreferredSize(new java.awt.Dimension(200, 45));
        jPanel16.setLayout(new java.awt.BorderLayout());

        jLabel13.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel13.setText("jLabel13");
        jLabel13.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        jPanel16.add(jLabel13, java.awt.BorderLayout.CENTER);

        sidePanel.add(jPanel16);

        signInPanel.setBackground(new java.awt.Color(0, 204, 0));
        signInPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signInPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signInPanelMouseClicked(evt);
            }
        });

        signInLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        signInLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user.png"))); // NOI18N
        signInLabel.setText("SIGN IN");

        javax.swing.GroupLayout signInPanelLayout = new javax.swing.GroupLayout(signInPanel);
        signInPanel.setLayout(signInPanelLayout);
        signInPanelLayout.setHorizontalGroup(
            signInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(signInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(signInPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(signInLabel)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        signInPanelLayout.setVerticalGroup(
            signInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(signInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(signInPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(signInLabel)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));

        navigatorPanel.setBackground(new java.awt.Color(255, 255, 204));

        cardViewButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/grid.png"))); // NOI18N
        cardViewButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 15));
        cardViewButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cardViewButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cardViewButtonMouseClicked(evt);
            }
        });

        listViewButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/list.png"))); // NOI18N
        listViewButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listViewButtonMouseClicked(evt);
            }
        });

        jTextField1.setVerifyInputWhenFocusTarget(false);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search_b.png"))); // NOI18N

        javax.swing.GroupLayout navigatorPanelLayout = new javax.swing.GroupLayout(navigatorPanel);
        navigatorPanel.setLayout(navigatorPanelLayout);
        navigatorPanelLayout.setHorizontalGroup(
            navigatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navigatorPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(45, 45, 45)
                .addComponent(listViewButton)
                .addGap(18, 18, 18)
                .addComponent(cardViewButton)
                .addGap(4, 4, 4))
        );
        navigatorPanelLayout.setVerticalGroup(
            navigatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigatorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(navigatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1)
                    .addGroup(navigatorPanelLayout.createSequentialGroup()
                        .addGroup(navigatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(navigatorPanelLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel10))
                            .addComponent(cardViewButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(listViewButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        parentCardLayout.setBackground(new java.awt.Color(255, 255, 255));
        parentCardLayout.setLayout(new java.awt.CardLayout());

        homePanel.setBackground(new java.awt.Color(153, 255, 204));

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 795, Short.MAX_VALUE)
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 444, Short.MAX_VALUE)
        );

        parentCardLayout.add(homePanel, "label");

        statisticsPanel.setBackground(new java.awt.Color(51, 255, 204));
        statisticsPanel.setLayout(new java.awt.BorderLayout());

        jButton1.setText("Click here");
        statisticsPanel.add(jButton1, java.awt.BorderLayout.CENTER);

        parentCardLayout.add(statisticsPanel, "button");

        listViewScrollPane.setBackground(new java.awt.Color(255, 255, 255));
        listViewScrollPane.setBorder(null);
        listViewScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        listConferencePanel.setBackground(new java.awt.Color(255, 255, 255));
        listConferencePanel.setLayout(new java.awt.GridLayout(0, 1, 0, 10));
        listViewScrollPane.setViewportView(listConferencePanel);

        parentCardLayout.add(listViewScrollPane, "card5");

        cardViewScrollPane.setBackground(new java.awt.Color(255, 255, 255));
        cardViewScrollPane.setBorder(null);
        cardViewScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        cardConferencePanel.setLayout(new java.awt.GridLayout(0, 3, 10, 10));
        cardViewScrollPane.setViewportView(cardConferencePanel);

        parentCardLayout.add(cardViewScrollPane, "card6");

        detailConferenceScrollPane.setBorder(null);
        detailConferenceScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        detailConferenceScrollPane.setPreferredSize(new java.awt.Dimension(794, 444));

        detailConferencePanel.setBackground(new java.awt.Color(255, 255, 255));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setPreferredSize(new java.awt.Dimension(0, 35));

        backToListLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        backToListLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
        backToListLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backToListLabelMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        jLabel7.setText("Enroll Now");
        jLabel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(backToListLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(18, 18, 18))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(backToListLabel))
                .addGap(0, 1, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        detailImageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(detailImageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(detailImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setPreferredSize(new java.awt.Dimension(794, 50));
        jPanel8.setLayout(new java.awt.BorderLayout());

        detailNameLabel.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        detailNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        detailNameLabel.setText("Name of Conference");
        detailNameLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel8.add(detailNameLabel, java.awt.BorderLayout.CENTER);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setLayout(new java.awt.BorderLayout());

        detailDescriptionLabel.setEditable(false);
        detailDescriptionLabel.setColumns(20);
        detailDescriptionLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        detailDescriptionLabel.setRows(5);
        detailDescriptionLabel.setAutoscrolls(false);
        detailDescriptionLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        jScrollPane2.setViewportView(detailDescriptionLabel);

        jPanel12.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        jPanel13.setLayout(new java.awt.GridLayout(0, 1));

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabel11.setText("Thông tin tham gia:");
        jPanel13.add(jLabel11);

        detailTimeLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        detailTimeLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        detailTimeLabel.setText("Time");
        jPanel13.add(detailTimeLabel);

        detailLocationLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        detailLocationLabel.setText("Location");
        jPanel13.add(detailLocationLabel);

        detailMemberLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        detailMemberLabel.setText("jLabel14");
        jPanel13.add(detailMemberLabel);

        javax.swing.GroupLayout detailConferencePanelLayout = new javax.swing.GroupLayout(detailConferencePanel);
        detailConferencePanel.setLayout(detailConferencePanelLayout);
        detailConferencePanelLayout.setHorizontalGroup(
            detailConferencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, 797, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 797, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detailConferencePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        detailConferencePanelLayout.setVerticalGroup(
            detailConferencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailConferencePanelLayout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
        );

        detailConferenceScrollPane.setViewportView(detailConferencePanel);

        parentCardLayout.add(detailConferenceScrollPane, "card5");

        profilePanel.setBackground(new java.awt.Color(255, 255, 255));
        profilePanel.setPreferredSize(new java.awt.Dimension(794, 444));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_256.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        yourProfileLabel.setFont(new java.awt.Font("Corbel", 0, 36)); // NOI18N
        yourProfileLabel.setText("Your profile");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(yourProfileLabel)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(0, 18, Short.MAX_VALUE)
                    .addComponent(yourProfileLabel)
                    .addGap(0, 18, Short.MAX_VALUE)))
        );

        jPanel9.setBackground(new java.awt.Color(242, 234, 237));

        profile_emailLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        profile_emailLabel.setText("email");

        profile_nameLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        profile_nameLabel.setText("name");

        jLabel22.setFont(new java.awt.Font("Corbel", 0, 22)); // NOI18N
        jLabel22.setText("Old password");

        jLabel23.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 153, 255));
        jLabel23.setText("Password");

        jLabel24.setFont(new java.awt.Font("Corbel", 0, 22)); // NOI18N
        jLabel24.setText("New password");

        jLabel25.setFont(new java.awt.Font("Corbel", 0, 22)); // NOI18N
        jLabel25.setText("Username");

        jLabel26.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(51, 153, 255));
        jLabel26.setText("General Information");

        jLabel27.setFont(new java.awt.Font("Corbel", 0, 22)); // NOI18N
        jLabel27.setText("Retype new password");

        jLabel28.setFont(new java.awt.Font("Corbel", 0, 22)); // NOI18N
        jLabel28.setText("Email");

        profile_usrnameLabel.setFont(new java.awt.Font("Calibri", 2, 18)); // NOI18N
        profile_usrnameLabel.setText("username account");

        jLabel30.setFont(new java.awt.Font("Corbel", 0, 22)); // NOI18N
        jLabel30.setText("Name");

        profile_oldpassLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        profile_newPassLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        profile_reNewPassLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        profile_updateButton.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        profile_updateButton.setText("UPDATE");
        profile_updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profile_updateButtonActionPerformed(evt);
            }
        });

        profile_defaultButton.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        profile_defaultButton.setText("DEFAULT");
        profile_defaultButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profile_defaultButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30)
                            .addComponent(jLabel25)
                            .addComponent(jLabel28))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(profile_usrnameLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(profile_nameLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(profile_emailLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel24)
                            .addComponent(jLabel27)
                            .addComponent(profile_defaultButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(profile_oldpassLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(profile_newPassLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(profile_updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(profile_reNewPassLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(46, 46, 46))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(profile_usrnameLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(profile_nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(profile_emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(profile_oldpassLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(16, 16, 16)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(profile_newPassLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(profile_reNewPassLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profile_defaultButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profile_updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout profilePanelLayout = new javax.swing.GroupLayout(profilePanel);
        profilePanel.setLayout(profilePanelLayout);
        profilePanelLayout.setHorizontalGroup(
            profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePanelLayout.createSequentialGroup()
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        profilePanelLayout.setVerticalGroup(
            profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePanelLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        parentCardLayout.add(profilePanel, "card10");

        javax.swing.GroupLayout conferenceManagementPanelLayout = new javax.swing.GroupLayout(conferenceManagementPanel);
        conferenceManagementPanel.setLayout(conferenceManagementPanelLayout);
        conferenceManagementPanelLayout.setHorizontalGroup(
            conferenceManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 795, Short.MAX_VALUE)
        );
        conferenceManagementPanelLayout.setVerticalGroup(
            conferenceManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 444, Short.MAX_VALUE)
        );

        parentCardLayout.add(conferenceManagementPanel, "card8");

        javax.swing.GroupLayout userManagementPanelLayout = new javax.swing.GroupLayout(userManagementPanel);
        userManagementPanel.setLayout(userManagementPanelLayout);
        userManagementPanelLayout.setHorizontalGroup(
            userManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 795, Short.MAX_VALUE)
        );
        userManagementPanelLayout.setVerticalGroup(
            userManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 444, Short.MAX_VALUE)
        );

        parentCardLayout.add(userManagementPanel, "card9");

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(navigatorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(parentCardLayout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addComponent(navigatorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parentCardLayout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout rootPanelLayout = new javax.swing.GroupLayout(rootPanel);
        rootPanel.setLayout(rootPanelLayout);
        rootPanelLayout.setHorizontalGroup(
            rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rootPanelLayout.createSequentialGroup()
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(sidePanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(signInPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logoPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        rootPanelLayout.setVerticalGroup(
            rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rootPanelLayout.createSequentialGroup()
                .addComponent(logoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(signInPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1001, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeSidePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeSidePanelMouseClicked
        // TODO add your handling code here:
        navigatorPanel.setVisible(false);
        parentCardLayout.removeAll();
        parentCardLayout.add(homePanel);
        parentCardLayout.repaint();
        parentCardLayout.revalidate();
    }//GEN-LAST:event_homeSidePanelMouseClicked

    private void conferenceListSidePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_conferenceListSidePanelMouseClicked
        // TODO add your handling code here:        
        navigatorPanel.setVisible(true);
        if(typeView == 0)
        {
            parentCardLayout.removeAll();
            parentCardLayout.add(listViewScrollPane);
            parentCardLayout.repaint();
            parentCardLayout.revalidate();
        }else
        {
            parentCardLayout.removeAll();
            parentCardLayout.add(cardViewScrollPane);
            parentCardLayout.repaint();
            parentCardLayout.revalidate();
        }
    }//GEN-LAST:event_conferenceListSidePanelMouseClicked

    private void statisticsSidePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statisticsSidePanelMouseClicked
        // TODO add your handling code here:
        navigatorPanel.setVisible(true);
        parentCardLayout.removeAll();
        parentCardLayout.add(statisticsPanel);
        parentCardLayout.repaint();
        parentCardLayout.revalidate();
    }//GEN-LAST:event_statisticsSidePanelMouseClicked

    private void signInPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signInPanelMouseClicked
        // TODO add your handling code here:
        if(typeUser == -1)
        {
            LoginScreen loginDialog = new LoginScreen(this, rootPaneCheckingEnabled);
            loginDialog.setVisible(true);

            typeUser = loginDialog.getTypeAccount();
            displaySidePanel();  
            System.out.println("account: " + typeUser);
            try
            {
                account = AccountDAO.getAccount(loginDialog.getAccountID());
                signInLabel.setText("<html><body>Hi, <b><i>"+account.getTen()+"</i></b>!<br>SIGN OUT.</body></html>");
            }catch(NullPointerException e){}
        }
        else
        {
            typeUser = -1;
            account = null;
            JOptionPane.showMessageDialog(null, "Sign out success!");
            displaySidePanel();
            signInLabel.setText("SIGN IN");
            homeSidePanelMouseClicked(evt);
        }
    }//GEN-LAST:event_signInPanelMouseClicked

    private void backToListLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backToListLabelMouseClicked
        // TODO add your handling code here:
        if(typeView == 0)
        {
            listViewButtonMouseClicked(evt);
        }
        else
        {
            cardViewButtonMouseClicked(evt);
        }
    }//GEN-LAST:event_backToListLabelMouseClicked

    private void cardViewButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardViewButtonMouseClicked
        // TODO add your handling code here:
        navigatorPanel.setVisible(true);
        typeView = 1;
        
        parentCardLayout.removeAll();
        parentCardLayout.add(cardViewScrollPane);
        parentCardLayout.repaint();
        parentCardLayout.revalidate();
        
    }//GEN-LAST:event_cardViewButtonMouseClicked

    private void listViewButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listViewButtonMouseClicked
        // TODO add your handling code here:
        navigatorPanel.setVisible(true);
        typeView = 0;
        
        parentCardLayout.removeAll();
        parentCardLayout.add(listViewScrollPane);
        parentCardLayout.repaint();
        parentCardLayout.revalidate();
    }//GEN-LAST:event_listViewButtonMouseClicked

    private void profileSidePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileSidePanelMouseClicked
        // TODO add your handling code here:
        if(account != null)
        {
            if(typeUser == 0)
            {
                yourProfileLabel.setText("Admin profile");
            }
            profile_usrnameLabel.setText(account.getUsername());
            profile_nameLabel.setText(account.getTen());
            profile_emailLabel.setText(account.getEmail());

            parentCardLayout.removeAll();
            parentCardLayout.add(profilePanel);
            parentCardLayout.repaint();
            parentCardLayout.revalidate();
        }
        
        
    }//GEN-LAST:event_profileSidePanelMouseClicked

    private void profile_defaultButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profile_defaultButtonActionPerformed
        // TODO add your handling code here:
        if(account != null)
        {
            profile_nameLabel.setText(account.getTen());
            profile_emailLabel.setText(account.getEmail());
            
            profile_oldpassLabel.setText("");
            profile_newPassLabel.setText("");
            profile_reNewPassLabel.setText("");
        }
    }//GEN-LAST:event_profile_defaultButtonActionPerformed

    private void profile_updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profile_updateButtonActionPerformed
        // TODO add your handling code here:
        String currentName = profile_nameLabel.getText();
        String currentEmail = profile_emailLabel.getText();
        String currentOldPass = new String(profile_oldpassLabel.getPassword());
        String currentNewPass = new String(profile_newPassLabel.getPassword());
        String currentReNewPass = new String(profile_reNewPassLabel.getPassword());
        int id = account.getIdAccount();
        
        //checking password
        if(!currentName.isEmpty() && !currentEmail.isEmpty())
        {
            if(currentOldPass.isEmpty() && currentNewPass.isEmpty() && currentReNewPass.isEmpty())
            {
                int result = JOptionPane.showConfirmDialog(null , "Are you sure to change your profile?");
                if(result == JOptionPane.YES_OPTION)
                {
                    account.setTen(currentName);
                    account.setEmail(currentEmail);
                    boolean isUpdate = AccountDAO.updateAccount(account);
                    if(isUpdate)
                    {
                        JOptionPane.showMessageDialog(null, "Update success!");
                        account = AccountDAO.getAccount(id);
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "Can't update your profile right now!");
                    }
                }
            }
            else
            {
                if (currentNewPass.equals(currentReNewPass))
                {
                    if(currentNewPass.length() >= 6)
                    {
                        //checking old password in DB
                        try
                        {
                            String oldPassHased = SupportFile.getSecurePassword(currentOldPass);
                            int result = JOptionPane.showConfirmDialog(null , "Are you sure to change your profile?");
                            if (result == JOptionPane.YES_OPTION)
                            {
                                if(account.getPassword().equals(oldPassHased))
                                {
                                    String newPassHased = SupportFile.getSecurePassword(currentNewPass);
                                    account.setTen(currentName);
                                    account.setEmail(currentEmail);
                                    account.setPassword(newPassHased);
                                    boolean isUpdate = AccountDAO.updateAccount(account);
                                    if(isUpdate)
                                    {
                                        JOptionPane.showMessageDialog(null, "Update success!");
                                        account = AccountDAO.getAccount(id);
                                        
                                        profile_oldpassLabel.setText("");
                                        profile_newPassLabel.setText("");
                                        profile_reNewPassLabel.setText("");
                                    }
                                    else
                                    {
                                        JOptionPane.showMessageDialog(null, "Can't update your profile right now!");
                                    }
                                }
                                else
                                {
                                    JOptionPane.showMessageDialog(null, "Wrong old password!");
                                }
                            }

                        }catch(NoSuchAlgorithmException e)
                        {
                            JOptionPane.showMessageDialog(null, "Can't update your profile right now!");
                        }
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "New password needs to contain at least 6 characters!");
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Password not match!");
                }
            }
        }else
        {
            JOptionPane.showMessageDialog(null, "Name or email field(s) can't be empty");
        }
        
    }//GEN-LAST:event_profile_updateButtonActionPerformed

    private void setDetailConferencePanel(Conference conference)
    {
        navigatorPanel.setVisible(false);
        backToListLabel.setAutoscrolls(false);
        
        
        String image = conference.getHinhAnh();
        String name = conference.getTen();
        String detail = conference.getMoTaChiTiet();
        Date d = conference.getThoiGian();
        String time = String.valueOf("Thời gian: " +SupportFile.getCustomTimeString(d));
        Location l = conference.getLocation();
        String location = String.valueOf("Địa điểm: "+l.getTen() + " - " + l.getDiaChi());
        int m = conference.getNgThamDu();
        String member = String.valueOf("Số người tham dự: "+m);
        
        ImageIcon img = new javax.swing.ImageIcon(getClass().getResource(image));
        Image newImg = img.getImage().getScaledInstance(775, 500, Image.SCALE_DEFAULT);
        ImageIcon setLabel = new ImageIcon(newImg);
        
        detailImageLabel.setIcon(setLabel);
        detailDescriptionLabel.setText(detail);
        detailDescriptionLabel.setLineWrap(true);
        detailDescriptionLabel.setWrapStyleWord(true);
        detailNameLabel.setText(name);
        detailTimeLabel.setText(time);
        detailLocationLabel.setText(location);
        detailMemberLabel.setText(member);
    }
    
    private void displaySidePanel()
    {
        switch (typeUser) {
        // not logged in
            case -1:
                setStateSidePanel(false);
                break;
        // admin
            case 0:
                setStateSidePanel(true);
                break;
        // user
            case 1:
                setStateSidePanel(false);
                statisticsSidePanel.setVisible(true);
                profileSidePanel.setVisible(true);
                break;
            default:
                break;
        }
    }
    
    private void setStateSidePanel(boolean b)
    {
        jPanel16.setVisible(b);
        statisticsSidePanel.setVisible(b);
        conferenceManagementSidePanel.setVisible(b);
        userManagementSidePanel.setVisible(b);
        profileSidePanel.setVisible(b);
    }
    
    private void initDataFromDB()
    {       
        cardConferencePanel.removeAll();
        listConferencePanel.removeAll();       
        navigatorPanel.setVisible(true);
        
        List<Conference> listConference = ConferenceDAO.getListConference();
        int sizeList = listConference.size();
        
        if(sizeList > 0)
        {
            for(int i = 0; i< sizeList; i++)
            {
                Conference c = listConference.get(i);
                int id = c.getIdHoiNghi();
                JPanel j1 = new cardViewConference(id);
                j1.addMouseListener(new MouseAdapter() {
                    @Override
                    public void mouseClicked(MouseEvent e) {
                        setDetailConferencePanel(c);
                        parentCardLayout.removeAll();
                        parentCardLayout.add(detailConferenceScrollPane);
                        parentCardLayout.repaint();
                        parentCardLayout.revalidate();
                    }
                });
                
                JPanel j2 = new listViewConference(id);
                j2.addMouseListener(new MouseAdapter() {
                    @Override
                    public void mouseClicked(MouseEvent e) {
                        setDetailConferencePanel(c);
                        parentCardLayout.removeAll();
                        parentCardLayout.add(detailConferenceScrollPane);
                        parentCardLayout.repaint();
                        parentCardLayout.revalidate();
                    }
                    
                });
                //jPanel.setCursor(new Cursor(Cursor.HAND_CURSOR));
                cardConferencePanel.add(j1);
                listConferencePanel.add(j2);
            }
        }
        else
        {
            JLabel noti = new JLabel("Không có hội nghị nào diễn ra!");
            listConferencePanel.add(noti, BorderLayout.CENTER);
        }

    }
    
    private void settingComponents()
    {
        detailConferenceScrollPane.getVerticalScrollBar().setUnitIncrement(20);
        listViewScrollPane.getVerticalScrollBar().setUnitIncrement(15);
        cardViewScrollPane.getVerticalScrollBar().setUnitIncrement(15);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try
                {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                    new MainScreen().setVisible(true);
                }catch(Exception e)
                {
                    new MainScreen().setVisible(true);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backToListLabel;
    private javax.swing.JPanel cardConferencePanel;
    private javax.swing.JLabel cardViewButton;
    private javax.swing.JScrollPane cardViewScrollPane;
    private javax.swing.JPanel conferenceListSidePanel;
    private javax.swing.JLabel conferenceManagementLabel;
    private javax.swing.JPanel conferenceManagementPanel;
    private javax.swing.JPanel conferenceManagementSidePanel;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JPanel detailConferencePanel;
    private javax.swing.JScrollPane detailConferenceScrollPane;
    private javax.swing.JTextArea detailDescriptionLabel;
    private javax.swing.JLabel detailImageLabel;
    private javax.swing.JLabel detailLocationLabel;
    private javax.swing.JLabel detailMemberLabel;
    private javax.swing.JLabel detailNameLabel;
    private javax.swing.JLabel detailTimeLabel;
    private javax.swing.JPanel homePanel;
    private javax.swing.JPanel homeSidePanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel listConferencePanel;
    private javax.swing.JLabel listViewButton;
    private javax.swing.JScrollPane listViewScrollPane;
    private javax.swing.JPanel logoPanel;
    private javax.swing.JPanel navigatorPanel;
    private javax.swing.JPanel parentCardLayout;
    private javax.swing.JLabel profileLabel;
    private javax.swing.JPanel profilePanel;
    private javax.swing.JPanel profileSidePanel;
    private javax.swing.JButton profile_defaultButton;
    private javax.swing.JTextField profile_emailLabel;
    private javax.swing.JTextField profile_nameLabel;
    private javax.swing.JPasswordField profile_newPassLabel;
    private javax.swing.JPasswordField profile_oldpassLabel;
    private javax.swing.JPasswordField profile_reNewPassLabel;
    private javax.swing.JButton profile_updateButton;
    private javax.swing.JLabel profile_usrnameLabel;
    private javax.swing.JPanel rootPanel;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JLabel signInLabel;
    private javax.swing.JPanel signInPanel;
    private javax.swing.JPanel statisticsPanel;
    private javax.swing.JPanel statisticsSidePanel;
    private javax.swing.JPanel userManagementPanel;
    private javax.swing.JPanel userManagementSidePanel;
    private javax.swing.JLabel yourProfileLabel;
    // End of variables declaration//GEN-END:variables
}